services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
    volumes:
      - .:/usr/src/app
      - ./serviceAccountKey.json:/usr/src/app/serviceAccountKey.json
    command: node app.js