services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    volumes:
      - .:/app
      - /app/node_modules
      # - ./serviceAccountKey.json을 따로 배포, node_wsp_team1 폴더에 넣어놓기
    command: node app.js
