services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
    volumes:
      - .:/app
      - /app/node_modules
      - ./serviceAccountKey.json:/app/serviceAccountKey.json
    command: node app.js
